import Manager1 from "../../Assets/ProfIncharges/VicePre.jpg";
// import manager2 from "../../Assets/ProfIncharges/VicePre.jpg";
// import manager3 from "../../Assets/ProfIncharges/secyy.jpg";

// import image1 from '../images/hello.jpg'
// import arnav from '../images/arnav.jpeg'
// import kritika from '../images/kritika.jpeg'
const Menu = [
  {
    id: 1,
    image: Manager1,
    name: "ARNAV GOEL",
    branch: "mech",
    category: "core",
  },

  {
    id: 2,
    image: Manager1,
    name: "arnav",
    branch: "mech",
    category: "core",
  },

  {
    id: 3,
    image: Manager1,
    name: "arnav",
    branch: "mech",
    category: "it",
  },

  {
    id: 4,
    image: Manager1,
    name: "arnav",
    branch: "mech",
    category: "it",
  },

  {
    id: 5,
    image: Manager1,
    name: "arnav",
    branch: "mech",
    category: "dac",
  },

  {
    id: 6,
    image: Manager1,
    name: "arnav",
    branch: "mech",
    category: "dac",
  },
  {
    id: 7,
    image: Manager1,
    name: "arnav",
    branch: "mech",
    category: "dac",
  },
  {
    id: 8,
    image: Manager1,
    name: "arnav",
    branch: "mech",
    category: "dac",
  },
];

// export default Menu;

// const Menu = [
//   {
//     id: 1,
//     Name: "Mohit Gupta",
//     Photo: { Manager1 },
//     Branch: "Production and Industrial Engineering",
//     SAEDepartment: "Mechanical",
//     Team: "",
//     GitHublink: "https://github.com/mtg718",
//     LinkedIn: "https://www.linkedin.com/in/guptamohit321",
//     Email: "mg550286@gmail.com",
//   },
//   {
//     id: "2",
//     Name: "Rahul Siloniya ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1ChhDAwQxt4lA6Jr3BKm_qmhsf_1ZGVzP",
//     "Passing Year": "2025",
//     Branch: "IT",
//     "SAE Department": "IT",
//     "Team (SAE)": "",
//     "GitHub link": "github.com/rahulsiloniya",
//     LinkedIn: "https://www.linkedin.com/in/rahul-siloniya-64776a231",
//     Email: "rsiloniya@gmail.com",
//   },
//   {
//     id: "3",
//     Name: "Vaibhav Dharmani",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1QBWD90vNQGQk-99tYiZRcr7EftivQl_y",
//     "Passing Year": "2024",
//     Branch: "Mechanical ",
//     "SAE Department": "Vehicle Dynamics ",
//     "Team (SAE)": "",
//     "GitHub link": "N.A.",
//     LinkedIn: "https://www.linkedin.com/in/vaibhav-dharmani-aa91a7199",
//     Email: "dharmani.vaibhav2001@gmail.com",
//   },
//   {
//     id: "4",
//     Name: "Bhupeksh",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1WKvFGDhWdjXH-USdd8g2puF2c-qWsnZP",
//     "Passing Year": "2024",
//     Branch: "Mechanical engineering ",
//     "SAE Department": "Mechanical ",
//     "Team (SAE)": "",
//     "GitHub link": "Nil",
//     LinkedIn: "https://www.linkedin.com/in/bhupeksh-kaushik-360424222",
//     Email: "kaushikbhupeksh@gmail.com ",
//   },
//   {
//     id: "5",
//     Name: "Himatri",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=13sUnyNlqgSw4Iq4xswPlj2uxtO9odTU9",
//     "Passing Year": "2024",
//     Branch: "ELECTRICAL",
//     "SAE Department": "Battery",
//     "Team (SAE)": "",
//     "GitHub link": "github.com/Himatri",
//     LinkedIn: "linkedin.com/in/himatri-noonwal/",
//     Email: "him.noonwal2003@gmail.com",
//   },
//   {
//     id: "6",
//     Name: "Rithika Goddilla",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=18zo5Y0VeuQ1IeezpTF8KQ9h3C1I0mNvk",
//     "Passing Year": "2024",
//     Branch: "Mechanical",
//     "SAE Department": "Chassis",
//     "Team (SAE)": "",
//     "GitHub link": ".",
//     LinkedIn: "http://www.linkedin.com/in/rithika-goddilla-85a031230",
//     Email: "goddillarithika22@gmail.com",
//   },
//   {
//     id: "7",
//     Name: "VINAY SAINI ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=19KjWwBLUodMWyrUpR_uf5OjWdEJZeNWD",
//     "Passing Year": "2024",
//     Branch: "MECHANICAL ",
//     "SAE Department": "TRANSMISSION ",
//     "Team (SAE)": "",
//     "GitHub link": "NA",
//     LinkedIn: "https://www.linkedin.com/in/vinay-saini-6a3044241",
//     Email: "sainivinay013@gmail.com",
//   },
//   {
//     id: "8",
//     Name: "Himanshu Khatri ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1rZ3N6_R1MHQ4gR8ElaL4-PI3NakMUgLM",
//     "Passing Year": "2024",
//     Branch: "Production and industrial engineering ",
//     "SAE Department": "Transmission ",
//     "Team (SAE)": "",
//     "GitHub link": "https://github.com/Hk2107",
//     LinkedIn: '"www.linkedin.com/in/',
//   },
//   {
//     id: 'Hk2107"',
//     Name: "hkhatri2107@gmail.com",
//   },
//   {
//     id: "9",
//     Name: "Preetham A",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1zJBP6_0SjL88KxsyF5Uxc5kR2SfunEoP",
//     "Passing Year": "2024",
//     Branch: "Mechanical ",
//     "SAE Department": "VD , VI and Chassis",
//     "Team (SAE)": "",
//     "GitHub link": "https://github.com/EmulatedDragon",
//     LinkedIn: "https://www.linkedin.com/in/preetham-a-289628225/",
//     Email: "Preetham2532002@gmail.com",
//   },
//   {
//     id: "10",
//     Name: "Yeredla karnakar Reddy",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1c8is0zGkFYb1gzS3CPQDh7_vsURHuzFc",
//     "Passing Year": "2024",
//     Branch: "Mechanical Engineering ",
//     "SAE Department": "Mechanical Engineering ",
//     "Team (SAE)": "",
//     "GitHub link": "NA",
//     LinkedIn: "https://www.linkedin.com/in/yeredla-karnakar-reddy-30a233224",
//     Email: "karnakarreddyyeredla@nitkkr.ac.in",
//   },
//   {
//     id: "11",
//     Name: "Lisha Garg",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1j9jAKZdh5hFcNo3IsLbeTKUGwXZuxh9m",
//     "Passing Year": "2024",
//     Branch: "Electrical",
//     "SAE Department": "BMS, DAQ",
//     "Team (SAE)": "",
//     "GitHub link": "NA",
//     LinkedIn: "https://www.linkedin.com/in/lisha-garg-61373a211",
//     Email: "lisha317garg@gmail.com",
//   },
//   {
//     id: "12",
//     Name: "Tanuj",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1339qZHSQxMMNrjsBEDWAV9gYG5s_jJpl",
//     "Passing Year": "2024",
//     Branch: "Mechanical ",
//     "SAE Department": "Mechanical ",
//     "Team (SAE)": "",
//     "GitHub link": "NIA",
//     LinkedIn: "https://www.linkedin.com/in/tanuj-yadav-49ab6a241",
//     Email: "tanujkumar123001@gmail.com",
//   },
//   {
//     id: "13",
//     Name: "Nishchal",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1Qd4jR5vI4EqfzTnJSo9kDEOwFfCAaJHf",
//     "Passing Year": "2024",
//     Branch: "Mechanical",
//     "SAE Department": "Chassis",
//     "Team (SAE)": "Accelerons",
//     "GitHub link": "NA",
//     LinkedIn: "https://www.linkedin.com/in/nishchal2001/",
//     Email: "nfulavanshi@gmail.com",
//   },
//   {
//     id: "14",
//     Name: "Koilada bindu madhava ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=19pDgnzoWHE3zfpDd-woDVOCtlVvZ2Kas",
//     "Passing Year": "2024",
//     Branch: "Mechanical engineering ",
//     "SAE Department": "Chassis ",
//     "Team (SAE)": "Team accelerons ",
//     "GitHub link": "https://github.com/dashboard",
//     LinkedIn:
//       "https://www.linkedin.com/feed/?trk=guest_homepage-basic_google-one-tap-submit",
//     Email: "bindumadhavakoilada@gmail.com",
//   },
//   {
//     id: "15",
//     Name: "Aniruddha Dubey",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=13qlucW-BkGzTwhLzkexZvFmm3n2seOyZ",
//     "Passing Year": "2024",
//     Branch: "Electrical Engineering",
//     "SAE Department": "EV",
//     "Team (SAE)": "Nitrox",
//     "GitHub link": "NA",
//     LinkedIn: "NA",
//     Email: "aniruddhadubey4@gmail.com",
//   },
//   {
//     id: "16",
//     Name: "Sourabh",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1eQkJnhXSm8vQzqQvZjA4nbC6BE8AhJuF",
//     "Passing Year": "2024",
//     Branch: "EE",
//     "SAE Department": "It team ",
//     "Team (SAE)": "It team",
//     "GitHub link": "https://github.com/sourabh707",
//     LinkedIn: "https://www.linkedin.com/in/sourabh2003/",
//     Email: "Buckalsourabh@gmail.com",
//   },
//   {
//     id: "17",
//     Name: "CHIRAG JANGRA",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1WQZamUV4HIQBWBHu2STGiEV53pVQSa58",
//     "Passing Year": "2026",
//     Branch: "ELECTRICAL ",
//     "SAE Department": "EELECTRICAL",
//     "Team (SAE)": "NITROX",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "chiragjangra268@gmail.com",
//   },
//   {
//     id: "18",
//     Name: "R Abinaya ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1Qa1USPGHIJLvcGmUPFa8gNJL80h4sVqe",
//     "Passing Year": "2024",
//     Branch: "Mechanical engineering ",
//     "SAE Department": "Brakes",
//     "Team (SAE)": "Nitrox",
//     "GitHub link": "",
//     LinkedIn: "https://www.linkedin.com/in/r-abinaya-aa9a691a0",
//     Email: "r_12016149@nitkkr.ac.in",
//   },
//   {
//     id: "19",
//     Name: "Garima Gupta ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1ge0fPXdtU7A5MKjfXeVa3ECwQ4UfZ2OQ",
//     "Passing Year": "2024",
//     Branch: "PIE",
//     "SAE Department": "Transmission ",
//     "Team (SAE)": "Nitrox ",
//     "GitHub link": "",
//     LinkedIn: "https://www.linkedin.com/in/garima-gupta-a11081221",
//     Email: "ggupta2607@gmail.com",
//   },
//   {
//     id: "20",
//     Name: "Pritam Beriwal ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1xJKKF6n_TI8CqcmzLUWvaF50GomelDPW",
//     "Passing Year": "2026",
//     Branch: "Mechanical ",
//     "SAE Department": "Vehicle dynamics ",
//     "Team (SAE)": "Nitrox ",
//     "GitHub link": "",
//     LinkedIn: "Pritam Beriwal ",
//     Email: "pritamberiwal91@gmail.com",
//   },
//   {
//     id: "21",
//     Name: "Vishesh Garg",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1IBgJ3kULqv9nhlNti0qCVFk7BpjQiHT8",
//     "Passing Year": "2025",
//     Branch: "IT",
//     "SAE Department": "IT",
//     "Team (SAE)": "IT Department",
//     "GitHub link": "https://github.com/VisheshGrg",
//     LinkedIn: "www.linkedin.com/in/vishesh-garg-07580622b",
//     Email: "gargvishesh95885@gmail.com",
//   },
//   {
//     id: "22",
//     Name: "Aryan Kushan",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1r3byWSnT6VaM6tJ5YA2B9d0vj3yieB04",
//     "Passing Year": "2025",
//     Branch: "Mechanical Engineering",
//     "SAE Department": "Vehicle Dynamics",
//     "Team (SAE)": "Nitrox",
//     "GitHub link": "",
//     LinkedIn: "https://www.linkedin.com/in/aryan-kushan-048415250",
//     Email: "kushan8nov@gmail.com",
//   },
//   {
//     id: "23",
//     Name: "LAKSHMINARAYAN ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1Raz4fxf1WSDtHj5W1GFySa1Nk32VoZ8_",
//     "Passing Year": "2026",
//     Branch: "MECHANICAL ",
//     "SAE Department": "TRANSMISSION ",
//     "Team (SAE)": "NITROX,NIT KURUKSHETRA ",
//     "GitHub link": "",
//     LinkedIn: "Lakshmi Narayan ",
//     Email: "12216076@nitkkr.ac.in",
//   },
//   {
//     id: "24",
//     Name: "Romit kumar",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=18gsSDFMPQgwYRo0Ut3t5Yw1e-uPoS30y",
//     "Passing Year": "2026",
//     Branch: "Mechanical",
//     "SAE Department": "Brakes",
//     "Team (SAE)": "Nitrox",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "romitkumar066@gmail.com",
//   },
//   {
//     id: "25",
//     Name: "Parv Sarin",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1be0aDG0NUZc3PeqifdHGFOfOWkFmAup3",
//     "Passing Year": "2024",
//     Branch: "Electrical",
//     "SAE Department": "Battery",
//     "Team (SAE)": "Nitrox",
//     "GitHub link": "Github.com/BeastParv",
//     LinkedIn: "Linkedin.com/in/parv-sarin",
//     Email: "Parvsarin01@gmail.com",
//   },
//   {
//     id: "26",
//     Name: "Aryan Sharma",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1gwuFegEQtHdYqO9_2AzFthFQiDWfwh_c",
//     "Passing Year": "2025",
//     Branch: "Mechanical Engineering",
//     "SAE Department": "Vehicle Dynamics",
//     "Team (SAE)": "Nitrox",
//     "GitHub link": "",
//     LinkedIn: "https://www.linkedin.com/in/aryan-sharma-950684229",
//     Email: "sharmaaryanjmu@gmail.com",
//   },
//   {
//     id: "27",
//     Name: "Anmol",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=171dEjrpSAnEwERnfTtp7_XOyblI6QWwt",
//     "Passing Year": "2024",
//     Branch: "Production and industrial engineering ",
//     "SAE Department": "Transmission ",
//     "Team (SAE)": "Nitrox",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "anmolchaudhary854@gmail.com",
//   },
//   {
//     id: "28",
//     Name: "Vivek Kumar ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1vXEmV0-0dzQrgG4C18vsyIY26qHS7xmO",
//     "Passing Year": "2025",
//     Branch: "Mechanical engineering ",
//     "SAE Department": "Vehicle Dynamics ",
//     "Team (SAE)": "Nitrox ",
//     "GitHub link": "NA",
//     LinkedIn: "https://www.linkedin.com/in/vivek-kumar-787b96237",
//     Email: "vicky746586@gmail.com",
//   },
//   {
//     id: "29",
//     Name: "Sahaj kumar ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1d8hbvmDrP1-COvTeym4jExEJmCILI3us",
//     "Passing Year": "2026",
//     Branch: "Mechanical ",
//     "SAE Department": "Transmission ",
//     "Team (SAE)": "Nitrox ",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "imssahaj@gmail.com",
//   },
//   {
//     id: "30",
//     Name: "Just to check",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1PGkeBO98vBBeWKZy_W-VikMexxG3S50m",
//     "Passing Year": "26177",
//     Branch: "Mechanical",
//     "SAE Department": "IT",
//     "Team (SAE)": "IT",
//     "GitHub link": "Gnak",
//     LinkedIn: "Ajjaj",
//     Email: "Check",
//   },
//   {
//     id: "31",
//     Name: "Madhuri kumari",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1kZI12LoOT5Hi6Ept6FPmjMUCFLzOXk4g",
//     "Passing Year": "2026",
//     Branch: "ELECTRONICS AND COMMUNICATION ",
//     "SAE Department": "DAQ",
//     "Team (SAE)": "ACCELERONE",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "kashyapmadhu1231@gmail.com",
//   },
//   {
//     id: "32",
//     Name: "Jatin",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1qjoDhg3x4r-8XgQuj2bqSIJKphyhzc9A",
//     "Passing Year": "2026",
//     Branch: "Electrical engineering ",
//     "SAE Department": "Electrical ",
//     "Team (SAE)": "Accelerons ",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "jatinkhairwal2003@gmail.com",
//   },
//   {
//     id: "33",
//     Name: "Mohit Chaudhary ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1GuSqR4p7RH4dFp3wREF8VxqoSNwioeWi",
//     "Passing Year": "2026",
//     Branch: "Mechanical engineering ",
//     "SAE Department": "VD",
//     "Team (SAE)": "Nitrox ",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "mohitchaudhary1325@gmail.com",
//   },
//   {
//     id: "34",
//     Name: "Sarthak Anand ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1bnZQhzsXmXirDpxoKUFwSlGNGT9SzMs-",
//     "Passing Year": "2026",
//     Branch: "Mechanical Engineering ",
//     "SAE Department": "Vehicle Dynamics ",
//     "Team (SAE)": "Accelerons ",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "sarthakanand2003@gmail.com",
//   },
//   {
//     id: "35",
//     Name: "Vipul Goyal ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1zkJtM2aWz8lWn74QPmWCXAOwGqYpuyI9",
//     "Passing Year": "2026",
//     Branch: "Information technology ",
//     "SAE Department": "DAQ",
//     "Team (SAE)": "Nitrox ",
//     "GitHub link": "https://github.com/VipulGoyal95",
//     LinkedIn: "https://www.linkedin.com/in/vipul-goyal-439210257",
//     Email: "vipulgoyal776@gmail.com",
//   },
//   {
//     id: "36",
//     Name: "Asmita Singh Vimal",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1F39Gh9fumIJturwWkxftgeNYxi1M77Ce",
//     "Passing Year": "2025",
//     Branch: "Mechanical engineering ",
//     "SAE Department": "Brakes",
//     "Team (SAE)": "Nitrox",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "asmita0782@gmail.com",
//   },
//   {
//     id: "37",
//     Name: "Abhishek",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=12tHcHqwSYIEjifrrlYIg3clvyJ7k2V_U",
//     "Passing Year": "2026",
//     Branch: "Electrical ",
//     "SAE Department": "Electrical ",
//     "Team (SAE)": "Accelerons ",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "abhi.abhishek.badgujar@gmail.com",
//   },
//   {
//     id: "38",
//     Name: "Check 2",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1oNQhmEpAf6O6hPyW-7DEbzUxRJMIwOpz",
//     "Passing Year": "Hshhw",
//     Branch: "Bshsj",
//     "SAE Department": "Bnsj",
//     "Team (SAE)": "Haj",
//     "GitHub link": "Jaj",
//     LinkedIn: "Haj",
//     Email: "Hsh",
//   },
//   {
//     id: "39",
//     Name: "Yash Arora ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1eiLg7fvwHjYZnmBXoLvyGDI4VgGASNXp",
//     "Passing Year": "2024",
//     Branch: "Production and Industrial Engineering ",
//     "SAE Department": "Engine and Transmission ",
//     "Team (SAE)": "Accelerone ",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "yash_12017032@nitkkr.ac.in",
//   },
//   {
//     id: "40",
//     Name: "Anand Malaiya ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1azxg-b3XsdosWuNzcbjQZEA9heGIOssd",
//     "Passing Year": "2026",
//     Branch: "Mechanical engineering ",
//     "SAE Department": "Transmission ",
//     "Team (SAE)": "Nitrox",
//     "GitHub link": "",
//     LinkedIn: "Anand Malaiya ",
//     Email: "anandmalaiya474@gmail.com",
//   },
//   {
//     id: "41",
//     Name: "Deekshith Nayak",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1CI3ceWPkAcJOJMyswMsSde-w9J3A30uW",
//     "Passing Year": "2024",
//     Branch: "Mechanical ",
//     "SAE Department": "Transmission ",
//     "Team (SAE)": "Team Accelerons ",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "deekshithramavath33@gmail.com",
//   },
//   {
//     id: "42",
//     Name: "Somya",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1yevzQ475VDuFk-vvDcdUMCMOXtc8Ey7K",
//     "Passing Year": "2026",
//     Branch: "ECE",
//     "SAE Department": "DAQ",
//     "Team (SAE)": "Accelerons",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "somya24arora@gmail.com",
//   },
//   {
//     id: "43",
//     Name: "Aditya Dabral ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1_oij8gyQ75l0xu8fv7v9-XWX2OnLuA_O",
//     "Passing Year": "2025",
//     Branch: "Mechanical ",
//     "SAE Department": "Vehicle Dynamics ",
//     "Team (SAE)": "Accelerons ",
//     "GitHub link": "Nil",
//     LinkedIn: "https://www.linkedin.com/in/aditya-dabral-294a6523a",
//     Email: "adityas.dabral@gmail.com",
//   },
//   {
//     id: "44",
//     Name: "ROHIT",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1LQQ8Z7YWREXqwwO-cx8548CLCUXF8SLK",
//     "Passing Year": "2026",
//     Branch: "ECE",
//     "SAE Department": "DAQ",
//     "Team (SAE)": "NITROX",
//     "GitHub link": "",
//     LinkedIn: '"https://www.linkedin.com/in/rohit-goyal',
//   },
//   {
//     id: '-94b592258"',
//     Name: "05rohitgoyal05@gmail.com",
//   },
//   {
//     id: "45",
//     Name: "Sweta Raj",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1eyeYApZB-z1v7YCXND6n3_-Jfz2TpZjC",
//     "Passing Year": "2026",
//     Branch: "Production and Industrial ",
//     "SAE Department": "Vechile Dynamics",
//     "Team (SAE)": "Nitrox",
//     "GitHub link": "",
//     LinkedIn: "linkedin.com/in/sweta-raj-b7a7681b6",
//     Email: "sraj672003@gmail.com",
//   },
//   {
//     id: "46",
//     Name: "Daksh Singh Chauhan ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=15Zx0l_5Oav6SOAG6l7VqYQ-pI_kkv4JC",
//     "Passing Year": "2026",
//     Branch: "Production and Industrial Engineering ",
//     "SAE Department": "Vehicle Dynamics",
//     "Team (SAE)": "Accelerons ",
//     "GitHub link": "https://github.com/DakshKing2003",
//     LinkedIn: "https://www.linkedin.com/in/daksh-singh-chauhan-03ab47255",
//     Email: "dakshsinghc27@gmail.com",
//   },
//   {
//     id: "47",
//     Name: "Aditya_Sheokand",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=12TVCAp3kdHUbAHdN5JboMUW-_bP7slqZ",
//     "Passing Year": "2025",
//     Branch: "Mechanical",
//     "SAE Department": "IT",
//     "Team (SAE)": "IT",
//     "GitHub link": "https://github.com/Aditya-Sheokand",
//     LinkedIn: "https://www.linkedin.com/in/aditya-sheokand-6b850722a/",
//     Email: "Adityasheokandofficial000@gmail.com",
//   },
//   {
//     id: "48",
//     Name: "Sanjana ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=16Tm8NTguo7HJAJpVaTMtXoF6EtNbyuyP",
//     "Passing Year": "2026",
//     Branch: "Mechanical ",
//     "SAE Department": "Transmission ",
//     "Team (SAE)": "Accelerons ",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "sanjanakatopuri@gmail.com",
//   },
//   {
//     id: "49",
//     Name: "Shubhayu Sinha ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1htGSnv_-umcqDTQgwndxDvdspr_odD6X",
//     "Passing Year": "2026",
//     Branch: "Mechanical ",
//     "SAE Department": "Vehicle Dynamics",
//     "Team (SAE)": "Nitrox",
//     "GitHub link": "",
//     LinkedIn: "https://www.linkedin.com/in/shubhayu-sinha-9a5053264",
//     Email: "shubhayu.sinha@gmail.com",
//   },
//   {
//     id: "50",
//     Name: "Keshav Mittal",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1j9izOvcw6GFTEUTzN4Z6-Xqh0j1fsmTX",
//     "Passing Year": "2025",
//     Branch: "Mechanical Engineering",
//     "SAE Department": "IT",
//     "Team (SAE)": "Webd",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "keshav_12016018@nitkkr.ac.in",
//   },
//   {
//     id: "51",
//     Name: "Kritika Agrawal ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1WbchExoc1866smzmZQJwHRN-wRWvHcGM",
//     "Passing Year": "2024",
//     Branch: "Production and Industrial Engineering ",
//     "SAE Department": "IT Team Head",
//     "Team (SAE)": "IT Team",
//     "GitHub link": "https://github.com/Kritikaagra",
//     LinkedIn: "https://www.linkedin.com/in/kritikaagra/",
//     Email: "kritika_12017030@nitkkr.ac.in",
//   },
//   {
//     id: "52",
//     Name: "LAKSHMINARAYAN ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1_RYcyWuxmkwnJbCp5SrmuNoKo5n94Xbe",
//     "Passing Year": "2026",
//     Branch: "MECHANICAL ",
//     "SAE Department": "TRANSMISSION ",
//     "Team (SAE)": "NITROX,NIT KURUKSHETRA ",
//     "GitHub link": "",
//     LinkedIn: "Lakshmi Narayan ",
//     Email: "12216076@nitkkr.ac.in",
//   },
//   {
//     id: "53",
//     Name: "Danish Goyal",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1wgUci6165NsWlbXWgIZOJUfiFhvHQSBT",
//     "Passing Year": "2026",
//     Branch: "Mechanical engineering ",
//     "SAE Department": "Vehicle dynamics",
//     "Team (SAE)": "Nitrox ",
//     "GitHub link": "",
//     LinkedIn: "Danish Goyal ",
//     Email: "danishgoyaljind15@gmail.com",
//   },
//   {
//     id: "54",
//     Name: "Prikshit chand anthal",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1-vKwrOLaZy-oboxrZDOnN6kxWzYAp42d",
//     "Passing Year": "2024",
//     Branch: "IT",
//     "SAE Department": "IT",
//     "Team (SAE)": "Acceleron",
//     "GitHub link": "https://github.com/Prikshit-anthal",
//     LinkedIn: "https://www.linkedin.com/in/prikshit-anthal-485ab1206/",
//     Email: "prikshitanthal@gmail.com",
//   },
//   {
//     id: "55",
//     Name: "Rahul Kumar Meena ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1yZex82JtBpCtwq3RXQmNIsXuCd_nEKww",
//     "Passing Year": "2025",
//     Branch: "Mechanical ",
//     "SAE Department": "Vehicle Dynamics ",
//     "Team (SAE)": "Accelerons ",
//     "GitHub link": "",
//     LinkedIn: "https://www.linkedin.com/in/rahul-kumar-meena-797138256",
//     Email: "rahulkm4723@gmail.com",
//   },
//   {
//     id: "56",
//     Name: "Navneet Raj",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1KnzvKoijL45YuKIqJNvCtUwzKPnW1J1i",
//     "Passing Year": "2024",
//     Branch: "Electrical ",
//     "SAE Department": "Daq website team",
//     "Team (SAE)": "Nitrox ",
//     "GitHub link": "",
//     LinkedIn: "https://www.linkedin.com/in/navneet-raj-94395a182",
//     Email: "navneetraj3695@gmail.com",
//   },
//   {
//     id: "57",
//     Name: "Bhavya",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1L0L-gDPEk9DfYJpjBmRgghquVrRIl648",
//     "Passing Year": "2024",
//     Branch: "PIE",
//     "SAE Department": "TRANSMISSION ",
//     "Team (SAE)": "Nitrox",
//     "GitHub link": "",
//     LinkedIn: "https://www.linkedin.com/in/bhavya-gevariya-99183b220",
//     Email: "Bhavyagevariya@gmail.com",
//   },
//   {
//     id: "58",
//     Name: "Sarvagya Agrawal ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1Pwiqz0L8mZlK5vD8TbIF18_P5rbbmoaS",
//     "Passing Year": "2026",
//     Branch: "Electrical ",
//     "SAE Department": "Battery",
//     "Team (SAE)": "Accelerons",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "12214084@nitkkr.ac.in",
//   },
//   {
//     id: "59",
//     Name: "Neha",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1gvcPu8j0yGqj7naFjX3Oj2_TsyX9wO6e",
//     "Passing Year": "2026",
//     Branch: "Mechanical ",
//     "SAE Department": "Brakes ",
//     "Team (SAE)": "Accelerons ",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "12216124@nitkkr.ac.in",
//   },
//   {
//     id: "60",
//     Name: "Sourav",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1AjYIyGvHCllBiXEpUPHTDcPytKduTRC2",
//     "Passing Year": "2025",
//     Branch: "Mechanical engineering",
//     "SAE Department": "Transmission",
//     "Team (SAE)": "Accelerons",
//     "GitHub link": "",
//     LinkedIn: "https://www.linkedin.com/in/sourav-kumar-691270284",
//     Email: "101souravkumar@gamil.com",
//   },
//   {
//     id: "61",
//     Name: "Abhishek Kumar",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1ceV69SV69XNRSjKXxfxP3JQuCTPE0enZ",
//     "Passing Year": "2024",
//     Branch: "Mechanical ",
//     "SAE Department": "IT",
//     "Team (SAE)": "Developer Team",
//     "GitHub link": "https://github.com/abhii30",
//     LinkedIn: "https://www.linkedin.com/in/abhii30/",
//     Email: "akumar300599@gmail.com",
//   },
//   {
//     id: "62",
//     Name: "Neha",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=10ea1hL8_BkRMW3JfZs3UoGLmfA-GrU5P",
//     "Passing Year": "2026",
//     Branch: "Mechanical engineering ",
//     "SAE Department": "Transmission",
//     "Team (SAE)": "Nitrox",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "nehabhadu104@gmail.com ",
//   },
//   {
//     id: "63",
//     Name: "Mukul Verma",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1rpEk58el58mGslZ61flARTr8KN0eKGJK",
//     "Passing Year": "2026",
//     Branch: "PIE",
//     "SAE Department": "Brake",
//     "Team (SAE)": "Nitrox",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "mukulv842@gmail.com",
//   },
//   {
//     id: "64",
//     Name: "Janardan ",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1pm5jz7skQ2iJtan8FbGyhF3n2TChQQYu",
//     "Passing Year": "2024",
//     Branch: "Electrical",
//     "SAE Department": "Motor and Motor Controller",
//     "Team (SAE)": "Accelerons",
//     "GitHub link": "",
//     LinkedIn: "",
//     Email: "nishantjamdgni@gmail.com",
//   },
//   {
//     id: "65",
//     Name: "Muskan",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1G0uhrMfuOII8S_1qbmou1KTDuvtabMyx",
//     "Passing Year": "2024",
//     Branch: "Cs",
//     "SAE Department": "It",
//     "Team (SAE)": "It team",
//     "GitHub link": "https://github.com/Muskan626bidani",
//     LinkedIn: "https://www.linkedin.com/in/muskan-bidani-a25016209",
//     Email: "muskan626bidani@gmail.com",
//   },
//   {
//     id: "66",
//     Name: "Nishchal",
//     Photo:
//       "https://drive.google.com/u/0/open?usp=forms_web&id=1zSgZFCkB6Gl90yfpZzmZF-LkP7RJ8h_8",
//     "Passing Year": "2024",
//     Branch: "Mechanical",
//     "SAE Department": "Chassis",
//     "Team (SAE)": "Accelerons",
//     "GitHub link": "NA",
//     LinkedIn: "www.linkedin.com/in/nishchal2001",
//     Email: "nfulavanshi@gmail.com",
//   },
// ];

export default Menu;
